# Generated by Django 3.0.5 on 2020-04-27 13:32

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('babies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventType', models.CharField(max_length=200)),
                ('eventNotes', models.CharField(max_length=200)),
                ('eventDate', models.DateTimeField(default=datetime.datetime(2020, 4, 27, 7, 32, 25, 666156))),
                ('babyId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='babies.Baby')),
            ],
        ),
    ]
