# Generated by Django 3.0.5 on 2020-04-25 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('babies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('eventId', models.CharField(max_length=300, primary_key=True, serialize=False)),
                ('eventType', models.CharField(max_length=200)),
                ('eventNotes', models.CharField(max_length=200)),
                ('eventDate', models.DateTimeField()),
                ('babyId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='babies.Baby')),
            ],
        ),
    ]
