# Generated by Django 3.0.5 on 2020-04-26 18:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20200426_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='eventDate',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 26, 12, 52, 49, 328677)),
        ),
    ]
