# Generated by Django 3.0.5 on 2020-04-27 06:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20200426_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='eventDate',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 27, 0, 22, 7, 959674)),
        ),
    ]
