# Generated by Django 3.0.5 on 2020-04-25 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Baby',
            fields=[
                ('babyId', models.CharField(max_length=300, primary_key=True, serialize=False)),
                ('babyName', models.CharField(max_length=200)),
                ('babyLastname', models.CharField(max_length=200)),
            ],
        ),
    ]
